routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

// admin routes
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('admin');

    Route::group(['prefix' => 'portfolios'], function () {
        Route::get('/', 'PortfolioController@portfolios')->name('viewListPortfolios');
        Route::get('/add', 'PortfolioController@view_add')->name('viewAddPortfolio');
        Route::post('/add', 'PortfolioController@add')->name('addPortfolio');
        Route::get('/edit/{portfolio}', 'PortfolioController@view_edit')->name('viewEditPortfolio');
        Route::post('/edit/{portfolio}', 'PortfolioController@edit')->name('editPortfolio');
        Route::delete('/delete/{portfolio}', 'PortfolioController@delete')->name('deletePortfolio');

    });

    Route::group(['prefix' => 'articles'], function () {
        Route::get('/', 'ArticleController@articles')->name('viewListArticles');
        Route::get('/add', 'ArticleController@view_add')->name('viewAddArticle');
        Route::post('/add', 'ArticleController@add')->name('addArticle');
        Route::get('/edit/{article}', 'ArticleController@view_edit')->name('viewEditArticle');
        Route::post('/edit/{article}', 'ArticleController@edit')->name('editArticle');
        Route::delete('/delete/{article}', 'ArticleController@delete')->name('deleteArticle');
    });

    // about_me routes
    Route::get('/about_me', 'DashboardController@view_about_me')->name('viewAboutMe');
    Route::post('/about_me', 'DashboardController@save_about_me')->name('saveAboutMe');

    // show messages
    Route::get('/messages', 'DashboardController@view_messages')->name('viewMessages');
    Route::get('/message/{contact}', 'DashboardController@view_single_message')->name('viewSingleMessage');

    // categories controller
    Route::resource('category', 'CategoryController');
    Route::group(['prefix' => 'categories'], function () {
        Route::get('/', 'CategoryController@index')->name('viewCategories');
        Route::post('/add', 'CategoryController@store')->name('addCategoriy');
        Route::put('/edit', 'CategoryController@update')->name('updateCategoriy');
    });

});

// website routes
Route::get('/', 'SiteController@home')->name('homePage');
Route::get('/about', 'SiteController@contact')->name('viewContactPage');
Route::get('portfolios/{portfolio_by_slug}', 'SiteController@portfolio_detail')->name('viewPortfolioPage');
Route::post('/contact', 'SiteController@submit_contact')->name('submitContactMessage');
Route::get('articles/{slug}', 'SiteController@article_page')->name('viewArticlePage');
Route::get('article', 'SiteController@articles_all')->name('viewArticles');
Route::get('/portfolio', 'SiteController@portfolios_all')->name('viewPortfolios');
Route::get('sitemap.xml','SitemapController@index');

Route::get('/category', 'SiteController@allCategories')->name('allCategories');
Route::get('/categories/{slug}', 'SiteController@singleCategory')->name('viewCategory');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{

    protected $fillable = ['parent_id', 'name', 'slug'];

    use Sluggable;

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'slug',
            ]
        ];
    }

    public function getLink()
    {
        return url('categories/'.$this->slug);
    }

    public function articles()
    {
        return $this->hasMany('App\Article');
    }

    public function children()
    {
        return $this->hasMany('App\Category', 'parent_id');
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;
use Illuminate\Validation\Rule;
use Morilog\Jalali\Jalalian;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::with('children')->whereNull('parent_id')->get();

        return view('admin.categories.index')->with([
            'categories' => $categories
        ]);
    }

    public function store(Request $request)
{
      $validatedData = $this->validate($request, [
            'name' => 'required|min:3|max:255|string',
            'slug' => 'required|min:3|max:255|string',
            'parent_id' => 'sometimes|nullable|numeric'
      ]);

      Category::create($validatedData);

      return redirect()->route('viewCategories')->withSuccess('notification', 'You have successfully created a Category!');
}

public function update(Request $request, Category $category)
{
        $validatedData = $this->validate($request, [
            'name'  => 'required|min:3|max:255|string',
            'slug' => 'required|min:3|max:255|string'
        ]);

        $category->update($validatedData);

        return redirect()->route('admin.categories.index')->with('notification', 'You have successfully updated a Category!');
}

public function destroy(Category $category)
{
        if ($category->children) {
            foreach ($category->children()->with('articles')->get() as $child) {
                foreach ($child->articles as $article) {
                    $article->update(['category_id' => NULL]);
                }
            }

            $category->children()->delete();
        }

        foreach ($category->articles as $article) {
            $article->update(['category_id' => NULL]);
        }

        $category->delete();

        return redirect()->route('category.index')->withSuccess('You have successfully deleted a Category!');
}


}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Article;

class CategoryController extends Controller
{
    //
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.panel')

@section('content')
<div class="container py-3">

    <div class="modal" tabindex="-1" role="dialog" id="editCategoryModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Edit Category</h5>

            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <form action="" method="POST">
            @csrf
            @method('POST')

            <div class="modal-body">
              <div class="form-group">
                <input type="text" name="name" class="form-control" value="" placeholder="Category Name" required>
              </div>
              <div class="form-group">
                <input type="text" name="slug" class="form-control" value="" placeholder="Category slug" required>
              </div>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
          </form>
      </div>
    </div>

  <div class="row">
    <div class="col-md-8">

      <div class="card">
        <div class="card-header">
          <h3>Categories</h3>
        </div>
        <div class="card-body">
          <ul class="list-group">
            @foreach ($categories as $category)
              <li class="list-group-item">
                <div class="d-flex justify-content-between">
                  <div class="col">
                    {{ $category->name }}
                  </div>
                  <div class="col">
                      {{ $category->slug}}
                  </div>
                  <div class="button-group d-flex">
                    <button type="button" id="editCategory" class="btn btn-sm btn-primary mr-1 edit-category" data-toggle="modal" data-target="#editCategoryModal" data-id="{{ $category->id }}" data-name="{{ $category->name }}">Edit</button>

                    {{-- Destroy category --}}
                    <form action="{{ route('category.destroy', $category->id) }}" method="POST">
                      @csrf
                      @method('DELETE')

                      <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                  </div>
                </div>

                {{-- Child category --}}
                @if ($category->children)
                  <ul class="list-group mt-2">
                    @foreach ($category->children as $child)
                      <li class="list-group-item">
                        <div class="d-flex justify-content-between">
                          {{ $child->name }}

                          <div class="button-group d-flex">
                            <button type="button" class="btn btn-sm btn-primary mr-1 edit-category" data-toggle="modal" data-target="#editCategoryModal" data-id="{{ $child->id }}" data-name="{{ $child->name }}">Edit</button>

                            <form action="{{ route('category.destroy', $child->id) }}" method="POST">
                              @csrf
                              @method('DELETE')

                              <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                          </div>
                        </div>
                      </li>
                    @endforeach
                  </ul>
                @endif
              </li>
            @endforeach
          </ul>
        </div>
      </div>
    </div>
    {{-- Create category --}}
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <h3>Create Category</h3>
        </div>

        <div class="card-body">
          <form action="{{ route('category.store') }}" method="POST">
            @csrf

            <div class="form-group">
              <select class="form-control" name="parent_id">
                <option value="">Select Parent Category</option>

                @foreach ($categories as $category)
                  <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
              </select>
            </div>

            <div class="form-group">
              <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Category Name" required>
            </div>
            <div class="form-group">
                <input type="text" name="slug" class="form-control" value="{{ old('slug') }}" placeholder="Category slug" required>
              </div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
    $('.edit-category').on('click', function() {
      var id = $(this).data('id');
      var name = $(this).data('name');
      var slug = $(this).data('slug');
      var url = "{{ route('updateCategoriy') }}" + id;

      $('#editCategoryModal form').attr('action', url);
      $('#editCategoryModal form input[name="name"]').val(name);
      $('#editCategoryModal form input[name="slug"]').val(slug);
    });
  </script>

@stop